Create wi_to_dwc.R
Rafnuss/camtraptor pull request #1
Opened 2022-07-27 13:33 UTC by Rafnuss

2022-07-27 13:51 UTC, peterdesmet requested changes

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      type = "Event", # Why not StillImage?
@tucotuco, should a observation based on a camera trap image have `type` "StillImage" or "Event"?

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      license = license, # take the licence from images.csv (note that there is also a licens for metatdata and the images themselves)
In the occurrence.csv, it should be the license of the data/metadata

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      bibliographicCitation:data_citation,
Only use this if it is different for every record

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      lifeStage = age,
Are these values controlled?

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      # organismID = , I don't understand what is the difference with taxon
This would be the `individual_id` (for marked individuals)

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      eventID = deployment_id,
Populate this with `image_id` for image-based observations, otherwise with `sequence_id` for observations based on groups of images.

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      parentEventID = project_id,
Add `deploymentID` here. Project ID will be ignored (but be the scope of the whole dataset)

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      eventDate = timestamp, # Is thi correct? time at which the photo was taken
Correct. For obs based on sequences, it could be a range.

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      locationID = placename,
Do the locations have an identifier/code?

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      genericName = species,
This should be removed. `genericName` is the genus part of the scientific name.

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      nameAccordingTo = "Wildlife Insight Taxonomy", # ?
I would drop this term, it is reserved for taxonomic checklists

2022-07-27 13:51 UTC, peterdesmet commented on R/wi_to_dwc.R
> +  readr::write_csv(
This should be replaced by a write_csv() that writes `dwc_audubon.csv` containing the image info, cf. https://github.com/inbo/camtraptor/blob/be0f1d0a7e13c3a74a3c7c23c240ed24ca12eaab/R/write_dwc.R#L217-L219

2022-07-27 13:58 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      lifeStage = age,
<img width="349" alt="image" src="https://user-images.githubusercontent.com/7571260/181265644-dfa7f4f6-e1ac-455e-a515-2653723c66e0.png">
Controlled means that they have a limited number of possible value, right? If so, then yes.

2022-07-27 14:01 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      lifeStage = age,
Great, please express those lowercase `male`, `female`, `unknown`. What about age?

2022-07-27 14:03 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      lifeStage = age,
<img width="349" alt="image" src="https://user-images.githubusercontent.com/7571260/181267018-7733e496-5ffc-4fba-b35a-57813a844b13.png">

2022-07-27 14:10 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      license = license, # take the licence from images.csv (note that there is also a licens for metatdata and the images themselves)
I don't fully understand what WI have a license at the project level and then at the photo level...I guess should use the project level `metadata_license` then?

2022-07-27 16:34 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      locationID = placename,
There is one in the website, but not in the exported file. I'll move `placename` to `locality` instead and remove `locationID`

2022-07-27 20:28 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      genericName = species,
Ok, but I still need `species` somewhere. Is `scientificName = paste0(genus," ",species),` correct?

2022-07-30 13:06 UTC, Rafnuss commented
@peterdesmet, Here is the report from the gbif validator on my dataset: 
https://www.gbif.org/tools/data-validator/6467d85c-2ec3-4db5-982f-832de2e75ce4.
Let me know if you have feedback. I'm not really sure about `deploymentRemark`.

2022-08-02 11:55 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      lifeStage = age,
Looks good, also write lowercase.

2022-08-02 11:58 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      license = license, # take the licence from images.csv (note that there is also a licens for metatdata and the images themselves)
Yes metadata_license for the occurrence records, photo level can be different and is expressed in the Audubon extension:

https://github.com/inbo/camtraptor/blob/be0f1d0a7e13c3a74a3c7c23c240ed24ca12eaab/inst/sql/dwc_audubon.sql#L38

2022-08-02 11:58 UTC, peterdesmet commented on R/wi_to_dwc.R
> +      genericName = species,
Yes, if you never end up with empty species or never have subspecies.

2022-08-02 11:59 UTC, peterdesmet commented
Apparently I need to be logged in to see that report. Can you send me another way?

2022-08-02 11:59 UTC, peterdesmet commented
Ignore, I can see it now.

2022-08-02 12:01 UTC, peterdesmet commented
Could you send me the produced file(s)?

2022-08-02 15:14 UTC, peterdesmet commented
Further feedback on the mapping:

- [ ] type: use `StillImage` after all (based on feedback from @tucotuco), unless the source is a video file
- [ ] rightsHolder: can this be derived from the project metadata
- [ ] datasetID: I would use the project ID or URL here (if no DOI is available)
- [ ] collectionCode: I would set this to `Wildlife Insights` (as a virtual collection) or (if known by that acronym) `WI` (currently does not seem to be used by [other collection](https://www.gbif.org/grscicoll/collection/search?q=wi&offset=20))
- [ ] recordedBy: what person is this, the person who set up the camera? I left this one out, because it's a machine obs
- [ ] behavior: can this be recorded in WI?
- [ ] occurrenceRemarks: I would put `individual_animal_notes` here
- [ ] eventID: either imageID or sequenceID, not deploymentID
- [ ] parentEventID: deploymentID, not projectID
- [ ] habitat: is this info available in WI (other than featuretype)
- [ ] samplingEffort: write as `YYYY-MM-DDTHH:MM:SSZ/YYYY-MM-DDTHH:MM:SSZ` (or just the dates), currently `2020-11-10 UTC--2021-02-10 UTC`
- [ ] locality: why are those the same values as eventID? Do they always look
- [ ] locationRemarks: I would put `featureType` here
- [ ] coordinateUncertaintyInMeters: is it possible to estimate this for all records?
- [ ] dateIdentified: is this information available?
- [ ] scientificName: can this be placed above kingdom?

2022-08-03 06:51 UTC, Rafnuss commented
> Further feedback on the mapping:
> 
> * [x]  type: use `StillImage` after all (based on feedback from @tucotuco), unless the source is a video file
> * [ ]  rightsHolder: can this be derived from the project metadata
There is a `project_admin_organization` (e.g. A Rocha Kenya) and `project_admin` (e.g. Raphael Nussbaumer)(as well as email). But this is different I thought? 
> * [ ]  datasetID: I would use the project ID or URL here (if no DOI is available)
The only field which might be helpful is : `data_citation` (e.g. "Nussbaumer, Raphaël\nKirao, Lennox\nJackson, Colin. 2019. Last updated July 2022. Dakatcha Woodland Biodiversity Assessment. http://n2t.net/ark:/63614/w12001317. Accessed via wildlifeinsights.org on 2022-07-26."). What do you think of extracting  `http://n2t.net/ark:/63614/w12001317` ? Is this equivalent to a doi? 
> * [x]  collectionCode: I would set this to `Wildlife Insights` (as a virtual collection) or (if known by that acronym) `WI` (currently does not seem to be used by [other collection](https://www.gbif.org/grscicoll/collection/search?q=wi&offset=20))
> * [x]  recordedBy: what person is this, the person who set up the camera? I left this one out, because it's a machine obs
It's also empty in my dataset, but I guess that it's possible to set it up on WI. I leave it out for now.
> * [ ]  behavior: can this be recorded in WI?
Not directly. There is the `remark` field but no designated one. Delete?
> * [x]  occurrenceRemarks: I would put `individual_animal_notes` here
> * [x]  eventID: either imageID or sequenceID, not deploymentID
Just to confirm that we have `image_id` on both `eventID` and `occurenceID`
> * [x]  parentEventID: deploymentID, not projectID
> * [x]  habitat: is this info available in WI (other than featuretype)
no, not that I can find.
> * [ ]  samplingEffort: write as `YYYY-MM-DDTHH:MM:SSZ/YYYY-MM-DDTHH:MM:SSZ` (or just the dates), currently `2020-11-10 UTC--2021-02-10 UTC`
> * [x]  locality: why are those the same values as eventID? Do they always look
No, this is particular to our case where we set up camera at new location every single time. (Don't ask me why....)
> * [x]  locationRemarks: I would put `featureType` here
> * [ ]  coordinateUncertaintyInMeters: is it possible to estimate this for all records?
Not sure how to do that generically... In our case, we measure position with the phone gps and then manually include the information on WI. But different location source would lead to different uncertainty, no? 
> * [ ]  dateIdentified: is this information available?
Strangely not. It is visible on the platform, but I cannot find it in the exported file. I've sent a request to WI about this. 
> * [x]  scientificName: can this be placed above kingdom?

2022-08-03 06:54 UTC, Rafnuss commented on R/wi_to_dwc.R
> +      genericName = species,
An suggestion how to write this more elegantly than this:
`ifelse(genus==""|species=="","",ifelse(species=="",genus,paste0(genus," ",species))`

2022-08-03 08:12 UTC, peterdesmet commented
- `rightsHolder`: This is one of the fields I let the user set in the function `write_dwc()`, because it's hard to derive from metadata
- `datasetID`: Yes http://n2t.net/ark:/63614/w12001317 would be very good as a datasetID (it's stable and it references a study/dataset uniquely)
- `behavior`: delete then
- `eventID`: "Just to confirm that we have image_id on both eventID and occurrenceID" yes correct. Since you are using image_id, I'm assuming that (for this dataset perhaps), you are not grouping observations (into one) for sequences?
- `coordinateUncertainty`: This is a really useful field to populate. `30` would be good default value when positions were recorded using GPS, so I would use that for your dataset. A bit trickier to use though as a generic value for the function (and other WI datasets).
-

2022-08-05 09:52 UTC, Rafnuss commented
@peterdesmet , I've added `rightsHolder` and `coordinateUncertainty` as parameter. What to you think of my suggestion to have WI `project_admin_organization` as default?

2022-08-05 09:57 UTC, peterdesmet commented
Yeah, that's probably a good default.

2022-08-07 11:39 UTC, peterdesmet commented
Are you not getting any `mediaID` returned by the WI export?

2022-08-07 11:41 UTC, peterdesmet commented
Or the `timestamp` (`xmp:CreateDate`) of the image? Which I assume is the timestamp of the observation?

2022-08-08 06:54 UTC, Rafnuss commented
> Are you not getting any `mediaID` returned by the WI export?

How would it be different from `image_id`?

> Or the timestamp (xmp:CreateDate) of the image? Which I assume is the timestamp of the observation?

 `timestamp` is used for the `eventDate`. 

I've set up my project as image based. Maybe sequence based project have a different export format?

2022-08-08 07:53 UTC, peterdesmet commented
- [ ] Can you add `mediaID` to Audubon and populate it with `image_id` (it's ok that this is a duplicate of `occurrenceID`)
- [ ] Can you add `CreateDate` to Audubon and populate it with timestamp?
- [ ] Can you correct typo in filename to `tests/testthat/test-write_dwc_wi.R`
- [ ] Can you rename directory to `wi_export_sample`?

2022-08-08 09:11 UTC, merged